language: ruby
cache: bundler

rvm:
  - 2.3.0
  - ruby-head

# Install bundler v2.0+
before_install:
  - gem update --system
  - gem install bundler

notifications:
  email:
    recipients:
      - maarten.bezemer@gmail.com
    on_failure: change
    on_success: never
